name: AWS Deploy Dev

on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    name: AWS deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh ./build-script.sh