name: AWS Deploy Prod

on:
  workflow_run:
    workflows: ["AWS Deploy Test"]
    branches: [develop]
    types: 
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Job build and deploy to PROD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh ./build-script.sh
      - name: Trigger E2E Tests
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: farmas/github-actions-child-test
          event-type: test-event