name: AWS Deploy Prod

on:
  workflow_run:
    workflows: ["AWS Deploy Test"]
    branches: [develop]
    types: 
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Job build and deploy to PROD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh ./build-script.sh